language: clojure
jdk:
  - openjdk8
  - openjdk11
env:
  global:
  - POSTGRESQL_DB_HOST=localhost
  - POSTGRESQL_DB_PORT=5432
  - POSTGRESQL_DB_USERNAME=postgres
  - POSTGRESQL_DB_PASSWORD=
services:
  - postgresql
addons:
  postgresql: "10"
before_script:
  - psql -U postgres -c 'CREATE DATABASE ktra_test;'
  - psql -U postgres ktra_test < db-def.sql
  - cp resources/config.edn_sample resources/config.edn
script:
  - lein test
