# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/ktra_test
      - image: cimg/postgres:16.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ktra_test
          POSTGRES_PASSWORD: testpwd

    working_directory: ~/repo

    resource_class: small
    environment:
      JVM_OPTS: -Xmx3200m
      POSTGRESQL_DB_USERNAME: postgres
      POSTGRESQL_DB_PASSWORD: testpwd

    steps:
      - checkout

      - run:
          name: database setup
          command: |
            sleep 5
            sudo apt install -y postgresql-client || true
            psql -d ${TEST_DATABASE_URL} < db-def.sql

      - run:
          name: setup config
          command: |
            cp resources/config.edn_sample resources/dev/config.edn

      - run:
          name: run tests
          command: clojure -T:build build && clojure -M:test

      - run:
          name: run linters
          command: |
            clojure -M:eastwood
            clojure -X:kibit

      - run:
          name: run clj-kondo
          command: |
            (cd /tmp
             curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
             chmod +x install-clj-kondo
             ./install-clj-kondo --dir /tmp)
             /tmp/clj-kondo --lint src test

      - run:
          name: run cljfmt
          command: |
            clojure -Ttools install io.github.weavejester/cljfmt '{:git/tag "0.11.2"}' :as cljfmt
            clojure -Tcljfmt check
