# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-bullseye
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/ktra_test
      - image: circleci/postgres:13-bullseye-ram
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ktra_test
          POSTGRES_PASSWORD: testpwd

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      POSTGRESQL_DB_USERNAME: postgres
      POSTGRESQL_DB_PASSWORD: testpwd

    steps:
      - checkout

      - run:
          name: database setup
          command: |
            sudo apt install -y postgresql-client || true
            psql -d ${TEST_DATABASE_URL} ktra_test < db-def.sql

      - run:
          name: setup config
          command: |
            cp resources/config.edn_sample resources/config.edn

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein test
