# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: clojure:temurin-24-tools-deps-bookworm-slim
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/ktra_test
      - image: cimg/postgres:17.5
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ktra_test
          POSTGRES_PASSWORD: testpwd

    working_directory: ~/repo

    resource_class: small
    environment:
      JVM_OPTS: -Xmx3200m
      POSTGRESQL_DB_USERNAME: postgres
      POSTGRESQL_DB_PASSWORD: testpwd

    steps:
      - checkout

      - run:
          name: database setup
          command: |
            sleep 5
            apt-get update && apt-get install -y postgresql-client
            psql -d ${TEST_DATABASE_URL} < db-def.sql

      - run:
          name: setup config
          command: |
            cp resources/config.edn_sample resources/dev/config.edn

      - run:
          name: run tests
          command: clojure -T:build build && clojure -X:test

      - run:
          name: run verification script
          command: |
            git clone https://github.com/terop/env-logger.git
            cp env-logger/scripts/verification.sh .
            CI=1 ./verification.sh
